# Generated by Django 5.1.6 on 2025-07-13 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('quartier', models.CharField(max_length=100)),
                ('nom_tuteur', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('contact_tuteur', models.CharField(max_length=20)),
                ('niveau_souhaite', models.CharField(choices=[('IDE', 'Infirmier Diplômé d’État'), ('SFDE', 'Sage-Femme Diplômée d’État'), ('ATS', 'Agent Technique de Santé'), ('ATSA', 'Agent Technique de Santé Accoucheuse'), ('TLDE', 'Technicien de Laboratoire Diplômé d’État')], max_length=50)),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('mode_formation', models.CharField(blank=True, max_length=50)),
                ('niveau_etude', models.CharField(choices=[('BAC', 'Baccalauréat'), ('BEF', 'BEF ou BEPC')], max_length=10)),
                ('document_pdf', models.FileField(upload_to='inscriptions/')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='identites/')),
                ('autre_document', models.FileField(blank=True, null=True, upload_to='autres_docs/')),
                ('commentaire', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejete', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinscriptions_inscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
