# Generated by Django 5.1.6 on 2025-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='lieu_naissance',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
