# Generated by Django 5.2.1 on 2025-07-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='École de Santé Le Bon Berger', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('mot_du_fondateur', models.TextField(blank=True)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('facebook', models.URLField(blank=True)),
                ('site_web', models.URLField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
