# Generated by Django 5.1.6 on 2025-08-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
