# Generated by Django 5.1.6 on 2025-07-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
