# Generated by Django 5.2.1 on 2025-07-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantuser',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
