# Generated by Django 5.1.6 on 2025-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_etudiantuser_code_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
